options:
  image_configuration:
    default: |
      pilot_image: 'pilot'  # values.pilot.image
      global_tag: '1.17.3'  # values.global.tag
      global_hub: 'docker.io/istio' # values.global.hub
      global_proxy_image: 'proxyv2' # values.global.proxy.image
      global_proxy_init_image: 'proxyv2' # values.global.proxy_init.image
      grpc_bootstrap_init: 'busybox:1.28'
    description: >
      YAML or JSON formatted input defining image configuration to use when installing the Istio control plane.
      For reference https://istio.io/v1.5/docs/reference/config/installation-options/
    type: string
  default-gateway:
    type: string
    default: istio-gateway
    description: Name to use as a default gateway
  gateway-service-name:
    type: string
    default: istio-ingressgateway-workload
    description: Name of the service created by istio-gateway to use as a Gateway
  ssl-crt:
    type: string
    default: ''
    description: |
        Base-64 certificate output. Can be set as follows:
          $ juju config ssl-crt="$(cat CERT_FILE | base64 -w0)"
        or on the bundle with: "include-base64://"
  ssl-key:
    type: string
    default: ''
    description: |
        Base-64 key output. Can be set as follows:
          $ juju config ssl-key="$(cat CERT_FILE | base64 -w0)"
        or on the bundle with: "include-base64://"
