options:
  cni-bin-dir:
    type: string
    default: ''
    description: Path to CNI binaries, e.g. /opt/cni/bin. This configuration option will only work when first deploying istio.
  cni-conf-dir:
    type: string
    default: ''
    description: Path to conflist files describing the CNI configuration, e.g. /etc/cni/net.d. This configuration option will only work when first deploying istio.
  default-gateway:
    type: string
    default: istio-gateway
    description: Name to use as a default gateway
  image-configuration:
    default: |
      pilot-image: 'pilot'  # values.pilot.image
      global-tag: '1.17.3'  # values.global.tag
      global-hub: 'docker.io/istio' # values.global.hub
      global-proxy-image: 'proxyv2' # values.global.proxy.image
      global-proxy-init-image: 'proxyv2' # values.global.proxy_init.image
      grpc-bootstrap-init: 'busybox:1.28'
    description: >
      YAML or JSON formatted input defining image configuration to use when installing the Istio control plane.
      For reference https://istio.io/v1.5/docs/reference/config/installation-options/
    type: string
  gateway-service-name:
    type: string
    default: istio-ingressgateway-workload
    description: Name of the service created by istio-gateway to use as a Gateway
